version: '3.8'
services:

  redis:
    container_name: redis-go
    image: redis
    env_file: ./src/.env
    # command: redis-server

    # command: redis-server --requirepass b5d64ee7995a60be928a189eeb294622fffa7fe3 
    command: 
      - /bin/sh
      - -c
      - redis-server --requirepass $${REDIS_PASS:?REDIS_PASS is not set} 
    volumes:
      - ./redisdata:/data
    restart: on-failure
    ports:
      - '6379:6379'

  postgres:
    container_name: postgres-go
    image: postgres:alpine
    env_file: ./src/.env
    environment:
      POSTGRES_USER: matt
      POSTGRES_PASSWORD: matt
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/data
    restart: on-failure
    ports:
      - '5432:5432'
